/*
  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  Permission is hereby granted, free of charge, to any person obtaining a copy of this
  software and associated documentation files (the "Software"), to deal in the Software
  without restriction, including without limitation the rights to use, copy, modify,
  merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#include <pgmspace.h>

#define SECRET
#define THINGNAME "heltec-v2"

const char *WIFI_SSID = "Angelo";
const char *WIFI_PASSWORD = "Pompeo00";
const char *AWS_IOT_ENDPOINT = "a3sii03p2pc56e-ats.iot.us-east-1.amazonaws.com";

  
// Amazon Root CA 1
static const char* AWS_CERT_CA PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";

// Device Certificate
static const char* AWS_CERT_CRT PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWjCCAkKgAwIBAgIVANSSIO5WmM70qJYpj2iRG2NjZ/I+MA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yNTAzMjkxMjMx
MDVaFw00OTEyMzEyMzU5NTlaMB4xHDAaBgNVBAMME0FXUyBJb1QgQ2VydGlmaWNh
dGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDH8YJSKT2JCZGCuCmm
uWW+ZOFhSCat0X8NvUT2FiCOoAoTozzpADENAKQoSW7J9CETiWNRWt6ymtKUQeL+
eqv5Ed8KWZJ+KorzHqu+Dn5eioeWjZrJLtDvbjTB26KYCXaPggV//j6FgIPgHtIj
qz/tsoS3RZrnypX3/wRuP8grnZ6avfehY7hh3ye0zy+AxMSd+SrTsJeg9Qt/4KF/
W+5N9bKmBmZlKaAsQVMFqFB9X1cWZYpdEWCUFqQEiikv/9ob3tr6BxXztwZhUnTc
Iey2jKgv08kmiIKwbAIERh76dIORRxr6U6Agnp1o7f5En7osaauqPG9LABuDHo1i
wrBPAgMBAAGjYDBeMB8GA1UdIwQYMBaAFPc6N5WDpzJSXSJw85STU7jS7u6uMB0G
A1UdDgQWBBR2PBwQmuFKca1y+0m4vnchWlIDrTAMBgNVHRMBAf8EAjAAMA4GA1Ud
DwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAQEALBuO5a1P+u0jIcIqx35k9YJK
s+4/eZHs4vPMteksZIRwPhySKFBEvJ6XvKXVHZzNU4k3OZanLaAic9N/khOrnOR3
EFqpdcirrADJQfiMipYx1C59rSBjUm/5U6JbFo1UI9NyZD7uNRzIr1uxx3Pr8E9v
kRq8AYGMS6nNq6h+qb7cOgcVFhhex91/0HYJhedIm5depmLBt9e4v4rskeAo5pH/
NLIKoFFzaCNhji7tiZ71/SUHa93xbWzB/UjF+2JWPxj4nuI89sTUU2dt7jMZ/s60
BMEmVKitJx4p5CxNOJ0qMQ+37yQGfMmy+2GhclQYz8sK63kBp9c8eujYhHv7kw==
-----END CERTIFICATE-----
)KEY";

// Device Private Key
static const char* AWS_CERT_PRIVATE PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAx/GCUik9iQmRgrgpprllvmThYUgmrdF/Db1E9hYgjqAKE6M8
6QAxDQCkKEluyfQhE4ljUVresprSlEHi/nqr+RHfClmSfiqK8x6rvg5+XoqHlo2a
yS7Q7240wduimAl2j4IFf/4+hYCD4B7SI6s/7bKEt0Wa58qV9/8Ebj/IK52emr33
oWO4Yd8ntM8vgMTEnfkq07CXoPULf+Chf1vuTfWypgZmZSmgLEFTBahQfV9XFmWK
XRFglBakBIopL//aG97a+gcV87cGYVJ03CHstoyoL9PJJoiCsGwCBEYe+nSDkUca
+lOgIJ6daO3+RJ+6LGmrqjxvSwAbgx6NYsKwTwIDAQABAoIBAGDCu/LPCnybKNQ+
E8ofxuFRKNFPfYh47ifUBN+i7baYNMg0I3IPKa3FNaxZfUg24Rr3Th09ALEmw+oD
yLqm2zr6LxpvJrnwFLZ7jVm44ecW2288sD/UbECy8M0wYYt6aOoiXk8G13L8MtXv
lHq2kYWS8y9OfBzYqaMOwzIno9OW5M5OFzt0gLtPt+NzX8Sqo5N/lZunLMt4QUTL
e9S0k3CZszlDfpnCENeyxPUcDJUinSJ368XZ17oncJX/lYIsIpGkzO3l4dwXk+WO
9wgxkvs3yes3jSKwmadlgYl71SacUGwJlO7Kjug22OijuRtVYVFFiVKzKCV0RuDM
1dokueECgYEA7GC/nOl7SnfQhLrCvDAP1fZGpnT5dQKZyv26lmZ7dGdRceYqOAou
A8DsQHLA7ov9qga4oAYMBeeiky+IqHFErQe1tGQ1K1PwUpS11ZAeUQiyPkncDpRC
Z2maBK+PSU2OGPv3jtbvwvKtj6oESlVUccDqAMtIpb66BJ8GINVhzesCgYEA2Ip+
KhUWypQCiR83Zdn4P2sy+e5y4LuROqfzOCKoCcKiBs2wZtCAIFPtffW5jehZCYVq
e9+Ud7tHlcbEIVL6SlDlliVPnCbiPiuTYi9vhDNNqt3qnhvddoz8V4w0Jlb5R4ys
jp8NObj8UAi/Q6ZWtQKsbY6OD8xsebYfJofu+i0CgYEApaf0AVqbngez6aEdIleo
cXGD99oYjQlCkMEax5aQxHY33NPKGLYBo33L1CrXzRXsswC82OEEAgtgozf31Nx0
nbK+g+qKXJAZ5zXy7PVwWaf3irGmd80tcF3Qo6IJj/y7LgU/bCpzozMBsaIcGaAN
ax8gn2fXxNiScvSjjdUdEvsCgYB3JIRUbTQUFCns/nMBpFOVuUrb/1nP0wQOTPhi
y5a/gAqcSbIkb9X/c445fukwbkYHGhRDwfmzgyTZAPtLBpfWKfqYiUDrPu2+nUVD
gawPBhdWyzFa+yP4JYx2MxtCeRpBRuJuuo6RUvnoo1dxRmVwxN7QjN4XTTfmI9Gx
5psTpQKBgCzwAbc34fwPaa9ZfbYssqXxVCv5MbB//mHNn48kEp0qYu2nqysXhNYv
xSobS7+LCU5nMc3XEflGmIWZroSHmAn8QrJMlykcOPrrYQ+9tYL5U4HfFneCpOSB
nhUq6EA2q/+zDfO+J7vouuqwdF2bq4YgPBOefQpXFsXkPe35GqoK
-----END RSA PRIVATE KEY-----
)KEY";
